#!/bin/bash
set -e

echo "🧩 Starting Plex Media Stack setup..."

# Ask for Plex claim token
read -p "🔑 Enter your Plex claim token (e.g., claim-xxxxxx): " plex_claim

# Create .env file
cat <<EOF > .env
# Generated by start.sh

PUID=1000
PGID=1000

QBT_USER=admin
QBT_PASS=adminadmin

PLEX_CLAIM=$plex_claim

RCLONE_REMOTE=mygdrive:
RCLONE_MOUNT_PATH=/media/gdrive
EOF

echo "✅ .env file created!"

# Create needed folders
echo "📁 Ensuring config and media folders exist..."
mkdir -p ./config/qbittorrent
mkdir -p ./config/sonarr
mkdir -p ./config/radarr
mkdir -p ./config/prowlarr
mkdir -p ./config/plex
mkdir -p ./config/proxy-manager
mkdir -p ./downloads
mkdir -p ./media/movies
mkdir -p ./media/shows

# Set permissions
echo "🔐 Setting permissions..."
sudo chown -R 1000:1000 ./config
sudo chown -R 1000:1000 ./downloads
sudo chown -R 1000:1000 ./media

# Start Docker Compose
echo "🐳 Starting Docker containers..."
docker compose up -d --build

echo "✅ All services started!"
echo ""
echo "📌 IMPORTANT: On first run, open qBittorrent at http://localhost:8080 and manually set:"
echo "   → Username: admin"
echo "   → Password: adminadmin"
echo ""
echo "💡 Then restart the autoconfig container:"
echo "   docker restart autoconfig"
